In [38]:
import pandas as pd
import spacy
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
import numpy as np
import itertools
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.datasets import fetch_20newsgroups

In [39]:
df = pd.read_csv("..\data/spam.csv", encoding = "ISO-8859-1")
del df["Unnamed: 2"]
del df["Unnamed: 3"]
del df["Unnamed: 4"]
df

v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [40]:
a={"ham": 0,
   "spam": 1}
df["v1"]= df['v1'].map(a)
df

v1                                                 v2
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...
...   ..                                                ...
5567   1  This is the 2nd time we have tried 2 contact u...
5568   0              Will Ì_ b going to esplanade fr home?
5569   0  Pity, * was in mood for that. So...any other s...
5570   0  The guy did some bitching but I acted like i'd...
5571   0                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [ ]:
## сделай позабытую лемматизацию

In [41]:
import spacy
from spacy.lookups import Lookups

def func(input):
    doc = nlp(input)
    data_lematized = "" 
    for word in doc:
        data_lematized += word.lemma_ + " "
    return data_lematized


nlp = spacy.load("en_core_web_sm")
df["v2"]=df["v2"].transform(func)


In [42]:
df

v1                                                 v2
0      0  go until jurong point , crazy .. available onl...
1      0                     ok lar ... joke wif u oni ... 
2      1  free entry in 2 a wkly comp to win FA Cup fina...
3      0  u dun say so early hor ... u c already then sa...
4      0  nah I do not think he go to usf , he live arou...
...   ..                                                ...
5567   1  this be the 2nd time we have try 2 contact u. ...
5568   0              will Ì _ b go to esplanade fr home ? 
5569   0  pity , * be in mood for that . so ... any othe...
5570   0  the guy do some bitching but I act like I woul...
5571   0                       rofl . its true to its name 

[5572 rows x 2 columns]

In [43]:
vect = CountVectorizer(min_df=10, stop_words='english', max_features=25)

tf = vect.fit_transform(df['v2'])
tempdf= pd.DataFrame(tf.A, columns=vect.get_feature_names_out())
tf.shape

(5572, 25)

In [44]:
tf

<5572x25 sparse matrix of type '<class 'numpy.int64'>'
	with 5682 stored elements in Compressed Sparse Row format>

In [45]:
tempdf

come  day  free  good  gt  home  just  know  like  love  ...  send  \
0        0    0     0     0   0     0     0     0     0     0  ...     0   
1        0    0     0     0   0     0     0     0     0     0  ...     0   
2        0    0     1     0   0     0     0     0     0     0  ...     0   
3        0    0     0     0   0     0     0     0     0     0  ...     0   
4        0    0     0     0   0     0     0     0     0     0  ...     0   
...    ...  ...   ...   ...  ..   ...   ...   ...   ...   ...  ...   ...   
5567     0    0     0     0   0     0     0     0     0     0  ...     0   
5568     0    0     0     0   0     1     0     0     0     0  ...     0   
5569     0    0     0     0   0     0     0     0     0     0  ...     0   
5570     0    0     1     0   0     0     0     0     1     0  ...     0   
5571     0    0     0     0   0     0     0     0     0     0  ...     0   

      stop  tell  text  think  time  today  txt  ur  want  
0        0     0     0      0     0      0    0   0     0  
1        0     0     0      0     0      0    0   0     0  
2        0     0     1      0     0      0    1   0     0  
3        0     0     0      0     0      0    0   0     0  
4        0     0     0      1     0      0    0   0     0  
...    ...   ...   ...    ...   ...    ...  ...  ..   ...  
5567     0     0     0      0     1      0    0   0     0  
5568     0     0     0      0     0      0    0   0     0  
5569     0     0     0      0     0      0    0   0     0  
5570     0     0     0      0     0      0    0   0     0  
5571     0     0     0      0     0      0    0   0     0  

[5572 rows x 25 columns]

In [46]:
vect.vocabulary_

{'ok': 13,
 'free': 2,
 'text': 18,
 'txt': 22,
 'say': 14,
 'think': 19,
 'like': 8,
 'send': 15,
 'home': 5,
 'want': 24,
 'today': 21,
 'day': 1,
 'time': 20,
 'make': 11,
 'ur': 23,
 'just': 6,
 'know': 7,
 'love': 9,
 'tell': 17,
 'need': 12,
 'lt': 10,
 'gt': 4,
 'good': 3,
 'come': 0,
 'stop': 16}

In [47]:
tf.todense()

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 1, ..., 1, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 1, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [48]:
df = pd.concat([df["v1"], tempdf], axis = 1)
df

v1  come  day  free  good  gt  home  just  know  like  ...  send  stop  \
0      0     0    0     0     0   0     0     0     0     0  ...     0     0   
1      0     0    0     0     0   0     0     0     0     0  ...     0     0   
2      1     0    0     1     0   0     0     0     0     0  ...     0     0   
3      0     0    0     0     0   0     0     0     0     0  ...     0     0   
4      0     0    0     0     0   0     0     0     0     0  ...     0     0   
...   ..   ...  ...   ...   ...  ..   ...   ...   ...   ...  ...   ...   ...   
5567   1     0    0     0     0   0     0     0     0     0  ...     0     0   
5568   0     0    0     0     0   0     1     0     0     0  ...     0     0   
5569   0     0    0     0     0   0     0     0     0     0  ...     0     0   
5570   0     0    0     1     0   0     0     0     0     1  ...     0     0   
5571   0     0    0     0     0   0     0     0     0     0  ...     0     0   

      tell  text  think  time  today  txt  ur  want  
0        0     0      0     0      0    0   0     0  
1        0     0      0     0      0    0   0     0  
2        0     1      0     0      0    1   0     0  
3        0     0      0     0      0    0   0     0  
4        0     0      1     0      0    0   0     0  
...    ...   ...    ...   ...    ...  ...  ..   ...  
5567     0     0      0     1      0    0   0     0  
5568     0     0      0     0      0    0   0     0  
5569     0     0      0     0      0    0   0     0  
5570     0     0      0     0      0    0   0     0  
5571     0     0      0     0      0    0   0     0  

[5572 rows x 26 columns]

## Классификация

In [49]:
pca = PCA(n_components=2)
X_pca = pca.fit_transform(tempdf, df["v1"])
X_pca

array([[-0.08675548, -0.1095981 ],
       [-0.09823166, -0.10185192],
       [-0.11688129,  0.33176894],
       ...,
       [-0.08675548, -0.1095981 ],
       [-0.07665177,  0.09443053],
       [-0.08675548, -0.1095981 ]])

In [50]:
class KNN:
    n_neighbors = 1
    metrics = {'minkowski': lambda X,Y: np.sqrt(np.sum(list(map(lambda x,y: np.abs(x-y)**2,X,Y)))),
              'euclidean': lambda X,Y:  np.sqrt(np.sum(list(map(lambda x,y: (x-y)**2,X,Y)))),
              'manhattan': lambda X,Y: np.sqrt(np.sum(list(map(lambda x,y: np.abs(x-y),X,Y))))}
    
    def __init__(self, metric='minkowski',p = 2,n_neighbors=1):
        self.n_neighbors = n_neighbors
        self.func = self.metrics[metric]
            
    def fit(self, X_train, y_train):
        self.X_train = np.array(X_train)
        self.index_array = np.arange(0, len(self.X_train))
        self.y_train = np.array(y_train)

    def predict(self, X_test):
        X_test = np.array(X_test)
        result = [] 
        
        for row in X_test:
            distance = list(itertools.repeat(row, len(X_test)))
            
            distance= map(self.func, distance, self.X_train)

            dict_distance = dict(zip(self.index_array, distance))
            sorted_distance = dict(sorted(dict_distance.items(), key=lambda item: item[1]))
            nearest_points = []
            keys = list(sorted_distance.keys())[:self.n_neighbors]
            positive = 0
            negative = 0
            
            for j in keys:
                if(self.y_train[j]==0):
                    negative+=1
                elif(self.y_train[j]==1):
                    positive+=1
                        
            if(negative>=positive):
                result.append(0)
            else:
                result.append(1)
        return np.array(result)

In [51]:
X_train, X_test, y_train, y_test = train_test_split(X_pca, df["v1"], test_size=0.2)

knn = KNN('minkowski', n_neighbors=5)

knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

confusion_matrix(y_test, y_pred)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.90      0.97      0.93       958
           1       0.67      0.34      0.45       157

    accuracy                           0.88      1115
   macro avg       0.78      0.66      0.69      1115
weighted avg       0.87      0.88      0.87      1115



ну норм, зато всего 2 признака)

## LDA

In [52]:
n_samples = 2000
n_topics = 10
n_top_words = 20

In [53]:
def print_top_words(model, feature_names, n_top_words):
    for topic_idx, topic in enumerate(model.components_):
        print("Topic #%d:" % topic_idx)
        print(" ".join([feature_names[i-1]
                        for i in topic.argsort()[:-n_top_words - 1:-1]]))

In [54]:
lda = LatentDirichletAllocation(n_components=n_topics, max_iter=20,
                                learning_method='online',
                                learning_offset=50.,
                                random_state=0).fit(df)

In [55]:
lda.components_.shape

(10, 26)

In [56]:
lda.components_

array([[1.00136870e-01, 3.24903800e+02, 1.00004646e-01, 1.00003740e-01,
        1.00004206e-01, 1.00001478e-01, 1.00079434e-01, 1.00002054e-01,
        1.00002187e-01, 1.00007661e-01, 1.00003103e-01, 1.00001506e-01,
        1.00006166e-01, 1.00004876e-01, 2.89344810e+02, 1.00006840e-01,
        1.00005936e-01, 1.00003532e-01, 1.00006695e-01, 1.00004470e-01,
        1.00004170e-01, 2.44500753e+02, 1.00007806e-01, 1.00004148e-01,
        1.00003600e-01, 1.00003708e-01],
       [1.00006908e-01, 1.00008496e-01, 1.00005437e-01, 1.00005153e-01,
        1.00004339e-01, 1.00001744e-01, 1.00008873e-01, 1.00002613e-01,
        1.00004991e-01, 1.00001737e-01, 1.00004976e-01, 1.00001754e-01,
        1.00005143e-01, 1.00005201e-01, 1.00002238e-01, 1.00005675e-01,
        1.00003494e-01, 1.00002249e-01, 1.00011282e-01, 1.00008008e-01,
        1.00002519e-01, 1.00006200e-01, 1.65555650e+02, 1.00004518e-01,
        1.00002703e-01, 2.47771142e+02],
       [1.00004739e-01, 1.00008818e-01, 1.00005453e-01

In [57]:
lda.transform(df).shape

(5572, 10)

In [58]:
print_top_words(lda, vect.get_feature_names_out(), 10)

Topic #0:
come ok time want home today like say tell make
Topic #1:
want today tell home come text want time say day
Topic #2:
know like stop make love come need time tell say
Topic #3:
gt lt free like time need send come make say
Topic #4:
send think make text just home stop want love free
Topic #5:
ur want txt tell free send love need good say
Topic #6:
love say need make free want like home time day
Topic #7:
just want know tell make say text free home txt
Topic #8:
want free text home stop txt ur send want time
Topic #9:
good day tell love today make ur come time home
