In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, cohen_kappa_score, confusion_matrix
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
data = pd.read_csv('train.csv')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59381 entries, 0 to 59380
Columns: 128 entries, Id to Response
dtypes: float64(18), int64(109), object(1)
memory usage: 58.0+ MB


In [ ]:
data.describe()

Id  Product_Info_1  Product_Info_3  Product_Info_4  \
count  59381.000000    59381.000000    59381.000000    59381.000000   
mean   39507.211515        1.026355       24.415655        0.328952   
std    22815.883089        0.160191        5.072885        0.282562   
min        2.000000        1.000000        1.000000        0.000000   
25%    19780.000000        1.000000       26.000000        0.076923   
50%    39487.000000        1.000000       26.000000        0.230769   
75%    59211.000000        1.000000       26.000000        0.487179   
max    79146.000000        2.000000       38.000000        1.000000   

       Product_Info_5  Product_Info_6  Product_Info_7       Ins_Age  \
count    59381.000000    59381.000000    59381.000000  59381.000000   
mean         2.006955        2.673599        1.043583      0.405567   
std          0.083107        0.739103        0.291949      0.197190   
min          2.000000        1.000000        1.000000      0.000000   
25%          2.000000        3.000000        1.000000      0.238806   
50%          2.000000        3.000000        1.000000      0.402985   
75%          2.000000        3.000000        1.000000      0.567164   
max          3.000000        3.000000        3.000000      1.000000   

                 Ht            Wt  ...  Medical_Keyword_40  \
count  59381.000000  59381.000000  ...        59381.000000   
mean       0.707283      0.292587  ...            0.056954   
std        0.074239      0.089037  ...            0.231757   
min        0.000000      0.000000  ...            0.000000   
25%        0.654545      0.225941  ...            0.000000   
50%        0.709091      0.288703  ...            0.000000   
75%        0.763636      0.345188  ...            0.000000   
max        1.000000      1.000000  ...            1.000000   

       Medical_Keyword_41  Medical_Keyword_42  Medical_Keyword_43  \
count        59381.000000        59381.000000        59381.000000   
mean             0.010054            0.045536            0.010710   
std              0.099764            0.208479            0.102937   
min              0.000000            0.000000            0.000000   
25%              0.000000            0.000000            0.000000   
50%              0.000000            0.000000            0.000000   
75%              0.000000            0.000000            0.000000   
max              1.000000            1.000000            1.000000   

       Medical_Keyword_44  Medical_Keyword_45  Medical_Keyword_46  \
count        59381.000000        59381.000000        59381.000000   
mean             0.007528            0.013691            0.008488   
std              0.086436            0.116207            0.091737   
min              0.000000            0.000000            0.000000   
25%              0.000000            0.000000            0.000000   
50%              0.000000            0.000000            0.000000   
75%              0.000000            0.000000            0.000000   
max              1.000000            1.000000            1.000000   

       Medical_Keyword_47  Medical_Keyword_48      Response  
count        59381.000000        59381.000000  59381.000000  
mean             0.019905            0.054496      5.636837  
std              0.139676            0.226995      2.456833  
min              0.000000            0.000000      1.000000  
25%              0.000000            0.000000      4.000000  
50%              0.000000            0.000000      6.000000  
75%              0.000000            0.000000      8.000000  
max              1.000000            1.000000      8.000000  

[8 rows x 127 columns]

In [ ]:
data.head().T

0         1         2         3         4
Id                         2         5         6         7         8
Product_Info_1             1         1         1         1         1
Product_Info_2            D3        A1        E1        D4        D2
Product_Info_3            10        26        26        10        26
Product_Info_4      0.076923  0.076923  0.076923  0.487179  0.230769
...                      ...       ...       ...       ...       ...
Medical_Keyword_45         0         0         0         0         0
Medical_Keyword_46         0         0         0         0         0
Medical_Keyword_47         0         0         0         0         0
Medical_Keyword_48         0         0         0         0         0
Response                   8         4         8         8         8

[128 rows x 5 columns]

In [ ]:
data_train,data_test = train_test_split(data, test_size=0.2)


In [ ]:
columns = ['Wt','Ht','Ins_Age','BMI']
max_nn = data_train.groupby('Response').count()['Id'].min()
knn10 = KNeighborsClassifier(n_neighbors=10)
knn100 = KNeighborsClassifier(n_neighbors=100)
knn1000 = KNeighborsClassifier(n_neighbors=1000)
knn10000 = KNeighborsClassifier(n_neighbors=10000)
knnmax = KNeighborsClassifier(n_neighbors = max_nn)

In [ ]:
y = data_train['Response']
x = pd.DataFrame(data_train, columns=columns)
knn10.fit(x,y)
knn100.fit(x,y)
knn1000.fit(x,y)
knn10000.fit(x,y)
knnmax.fit(x,y)

KNeighborsClassifier(n_neighbors=807)

In [ ]:
data_test=pd.DataFrame(data_test)
x_test=pd.DataFrame(data_test, columns=columns)
data_test['target_10'] = knn10.predict(x_test)
data_test['target_100'] = knn100.predict(x_test)
data_test['target_1000'] = knn1000.predict(x_test)
data_test['target_10000'] = knn10000.predict(x_test)
data_test['target_max']=knnmax.predict(x_test)

In [ ]:
print('kNN, 10:', cohen_kappa_score(data_test['target_10'],data_test['Response'], weights='quadratic'))
print('kNN, 100:', cohen_kappa_score(data_test['target_100'],data_test['Response'], weights='quadratic'))
print('kNN, 1000:', cohen_kappa_score(data_test['target_1000'],data_test['Response'], weights='quadratic'))
print('kNN, 10000:', cohen_kappa_score(data_test['target_10000'],data_test['Response'], weights='quadratic'))
print('kNN, max:', cohen_kappa_score(data_test['target_max'],data_test['Response'], weights='quadratic'))

kNN, 10: 0.28353231270707524
kNN, 100: 0.29403164085141253
kNN, 1000: 0.2685416788659938
kNN, 10000: 0.1447350413520585
kNN, max: 0.2704043243895493


In [ ]:
print (f1_score(data_test['target_10'], data_test['Response'], average='weighted'))
print (f1_score(data_test['target_100'], data_test['Response'], average='weighted'))
print (f1_score(data_test['target_1000'], data_test['Response'], average='weighted'))
print (f1_score(data_test['target_10000'], data_test['Response'], average='weighted'))

0.42541754992592506
0.4951220997564
0.5133900533461173
0.5224118025606957


In [ ]:
print (confusion_matrix(data_test['target_10'], data_test['Response']))
print (confusion_matrix(data_test['target_10000'], data_test['Response']))

[[ 204  166    9   11  112  192  145  163]
 [ 145  256   13    3  129  143   87  106]
 [   0    1    1    0    3    1    0    1]
 [   2    2    1    0    0    3    1    8]
 [ 112  163   43    5  328  173   45   37]
 [ 246  259   58   39  266  699  419  388]
 [ 116  132   20   31   95  273  249  254]
 [ 417  378   61  171  195  746  616 2935]]
[[   0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0]
 [ 540  709   94   25  680  945  454  187]
 [   0    0    0    0    0    0    0    0]
 [ 702  648  112  235  448 1285 1108 3705]]
